name: CI/CD workflow

on:
  push:
env:
  oo: ${{ secrets[format('abc_{0}', aaa )] }}
  repositoryName: dta-ct-app-web-dashboard
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo oo